### ISSUE TITLE
server-side-render vue

### ISSUE THREAD

**Issue by ilia-aaron** [FranzSkuffka/vue-medium-editor#48]
Hi! I have troubles with ssr & vue-medium-editor( 
```
ReferenceError: document is not defined
    at Object.<anonymous> (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:88:22)
    at Object.defineProperty.value (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:7918:30)
    at __webpack_require__ (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:30:30)
    at Object.module.exports (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:7931:21)
    at __webpack_require__ (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:30:30)
    at /node_modules/vue2-medium-editor/dist/vueMediumEditor.js:76:18
    at /node_modules/vue2-medium-editor/dist/vueMediumEditor.js:79:10
    at webpackUniversalModuleDefinition (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:3:20)
    at Object.<anonymous> (/node_modules/vue2-medium-editor/dist/vueMediumEditor.js:10:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
Have you any beta versions with ssr support?

**Comment by janwirth** [comment]
I think this issue lives within medium-editor. I have no experience with Vue SSR so far.

> Have you any beta versions with ssr support?

can you elaborate? :)

**Comment by janwirth** [comment]
Bump!

**Comment by janwirth** [comment]
Closing due to inactivity

**Comment by ilia-aaron** [comment]
@FranzSkuffka The problem is that there is no verification for `typeof(window) !== undefined` because ssr evaluate on server and server don't know about `window`

**Comment by janwirth** [comment]
Can you share a minimal reproduction example please?

**Comment by janwirth** [comment]
I see no occurence of window in the source code as of now.
https://github.com/FranzSkuffka/vue-medium-editor/search?utf8=%E2%9C%93&q=window
`@1.1.0`

**Comment by janwirth** [comment]
Please provide a minimal reproduction example.

**Comment by AnthonyConklin** [comment]
![image](https://user-images.githubusercontent.com/3253600/40593653-7cfa1812-61ef-11e8-84a5-4b609b2b4e10.png)
Same thing here... using SSR w/ Nuxt

**Comment by janwirth** [comment]
@AnthonyConklin I think you need to address this in the classList package, not here. Also, provide a minimal working example where I can reproduce this bug. That would be time spent more wisely than reacting to your own comment 😛

**Comment by AnthonyConklin** [comment]
Touche ;) I will setup a sample environment that reproduces this issue. I'll see if I can also submit a PR that resolves it. Thanks for the work!

**Comment by janwirth** [comment]
You're welcome! Thank you for the support :)
